### ISSUE TITLE
TIL 및 블로그 운영 관련 질문드립니다.

### ISSUE THREAD

**Issue by ghanIn-dev** [cheese10yun/TIL#2]
안녕하세요. 

TIL을 시작하려고 찾아보다,

가장 배우고싶은 모습으로 TIL과 블로그를 운영하시는 것 같아서 도움을 구하고싶습니다.

보기에 TIL과 블로그 포스팅이 연결되어 동작하는 것 같은데 어떤식으로 블로그 운영과 TIL을 기록하시는지 여쭤보고싶습니다.

질문
1. 사용하시는 문서(TIL)작성 툴
2. github에 문서를 업로드할시 블로그에 포스팅이 자동으로 되는 구조가 맞는지
3. 블로그 생성

감사합니다.

**Comment by cheese10yun** [comment]
질문 감사합니다. 

1. TIL 작성 툴 -> VS Code를 사용하고 있습니다. 필요한 이미지는 draw.io, 시퀀스 다이어그램은 plantuml을 사용하고 있습니다.
2. 자동으로 되지는 않습니다. github readme 파일을 만들고 최종적으로 파일 복사 스크립트 정도로만 사용하고 있습니다. 현재 hexo라는 블로그 템플릿을 사용하는데 좀 제약이 있다보니 완전히 자동으로는 어려움이 있습니다. 이거 때문에 다시 티스토리로 옮길 까도 생각중에 있어요
3. 블로그 생성? 은 어떤것을 여쭤보는 건지는 모르겠지만 node js 기반 hexo라는 블로그 템플릿을 사용하고 있습니다.
